export const ExperienceOptions = [
    "Beginner",
    "Less than 1 year",
    "1 Year",
    "2 Years",
    "3 Years",
    "4 Years",
    "5 Years",
    "6 Years",
    "7 Years",
    "8 Years",
    "9 Years",
    "10 Years",
    "More Than 10 Years",
    "More Than 15 Years",
    "More Than 20 Years",
]