// Define an array of profile options
export const profileOptions = [
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "UI/UX Designer",
    "Full Stack Developer",
    "React Developer",
    "MERN Stack Developer",
    "MEAN Stack Developer",
    "Angular Developer",
    "NodeJS Developer",
    "Laravel Developer",
    "PHP Developer",
    "Mobile App Developer",
    "Android Developer",
    "Python Developer",
    "Java Developer",
    "Software Engineer",
    "AI Developer",
    "Data Scientist",
    "DevOps Engineer",
    "Freelancer",
    "Cloud Architect",
    "Game Developer",
    "Blockchain Developer",
    "Machine Learning Engineer",
    "Product Manager",
    "Digital Marketer",
    "Cybersecurity Specialist",
    "Database Administrator",
    "Network Engineer",
    "QA Tester",
    "AI Researcher",
];
